# Generated by Django 5.2.1 on 2025-09-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariocustomizado',
            table='sales_usuariocustomizado',
        ),
    ]
