# Generated by Django 5.2.1 on 2025-09-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='baixada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_baixa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
